<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "client_whiteroom"
 *
 * Auto generated by Extension Builder 2016-11-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'whiteRoom Project Kickstart',
	'description' => '',
	'category' => 'distribution',
	'author' => 'Daniel Schoeneck',
	'author_email' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '10.1.1',
	'constraints' => [
	    'depends' => [
	        'php' => '8.0.0-8.2.99',
			'typo3' => '11.5.1-11.5.99',
			'indexed_search' => '11.5.1-11.5.99',
			'form' => '11.5.1-11.5.99',
			'seo' => '11.5.1-11.5.99',
			'fluid_styled_content' => '11.5.1-11.5.99',
			'impexp' => '11.5.1-11.5.99',
			'news' => '11.0.0-11.9.99',
			'rx_shariff' => '15.0.0-15.99.99',
			'vhs' => '7.0.0-7.0.99',
			'dp_cookieconsent' => '12.1.0-12.1.99'
	    ],
	    'conflicts' => [

	    ],
	    'suggests' => [

	    ]
	]
);
