<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "client_whiteroom"
 *
 * Auto generated by Extension Builder 2016-11-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'whiteRoom Project Kickstart',
	'description' => '',
	'category' => 'distribution',
	'author' => 'Daniel Schoeneck',
	'author_email' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '3.0.5',
	'constraints' => array(
		'depends' => array(
			'php' => '7.2.0-7.2.99',
			'typo3' => '9.5.00-9.5.99',
			'fluid_styled_responsive_images' => '8.7.0-8.7.99',
			'indexed_search' => '9.5.00-9.5.99',
			'news' => '7.2.0-7.2.99',
			'rx_shariff' => '12.0.0-12.99.99',
			'vhs' => '5.2.0-5.2.99',
			
		),
		'conflicts' => array(

		),
		'suggests' => array(

			'dp_cookieconsent' => '9.7.0-9.7.99',
			
		),
	),
);
