<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "client_whiteroom"
 *
 * Auto generated by Extension Builder 2016-11-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'whiteRoom Project Kickstart',
	'description' => '',
	'category' => 'distribution',
	'author' => 'Daniel Schoeneck',
	'author_email' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '2.5.0',
	'constraints' => array(
		'depends' => array(
			'php' => '7.0.0-7.2.99',
			'typo3' => '8.7.00-8.7.99',
			'fluid_styled_content' => '8.7.0-8.7.99',
			'fluid_styled_responsive_images' => '8.7.0-8.7.99',
			'indexed_search' => '8.7.0-8.7.99',
			//'flux' => '',
			//'fluidpages' => '',
			//'fluidcontent' => '',
			//'fluidcontent_core' => '',
			'news' => '7.1.0-7.2.99',
			'rx_shariff' => '12.0.0-12.99.99',
			'realurl' => '2.5.0-2.5.99',
			'vhs' => '5.2.0-5.2.99',
			'metaseo' => '3.0.0-3.0.99',
			
		),
		'conflicts' => array(
			'css_styled_content' => '',

		),
		'suggests' => array(
			
			'dd_googlesitemap' => '2.0.5-2.99.99',
		),
	),
);
