base: /
baseVariants: {  }
errorHandling: {  }
languages:
  -
    title: German
    enabled: true
    locale: de_DE.UTF-8
    hreflang: de-DE
    base: /
    websiteTitle: ''
    navigationTitle: Deutsch
    flag: de
    languageId: 0
  -
    title: English
    enabled: true
    locale: en_US.UTF-8
    hreflang: en-US
    base: /en/
    websiteTitle: ''
    navigationTitle: English
    fallbackType: strict
    fallbacks: '0'
    flag: en-us-gb
    languageId: 1
  -
    title: French
    enabled: true
    locale: fr_FR.UTF-8
    hreflang: fr-FR
    base: /fr/
    websiteTitle: ''
    navigationTitle: Français
    fallbackType: strict
    fallbacks: '1,0'
    flag: fr
    languageId: 2
rootPageId: 1
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: ''
    map:
      sitemap.xml: 1533906435
      ics: 9819
  News:
    type: Extbase
    limitToPages: [6]
    extension: News
    plugin: Pi1
    routes:
      - routePath: '/'
        _controller: 'News::list'
      - routePath: '/page-{page}'
        _controller: 'News::list'
        _arguments:
          page: 'currentPage'
      - routePath: '/{news_title}'
        _controller: 'News::detail'
        _arguments:
          news_title: news
      - routePath: '/{category_name}'
        _controller: 'News::list'
        _arguments:
          category_name: overwriteDemand/categories
      - routePath: '/{tag_name}'
        _controller: 'News::list'
        _arguments:
          tag_name: overwriteDemand/tags
    defaultController: 'News::list'
    defaults:
      page: '0'
    requirements:
      news_title: '^[a-zA-Z0-9].*$'
      page: \d+
    aspects:
      news_title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
      page:
        type: StaticRangeMapper
        start: '1'
        end: '99'
      category_name:
        type: PersistedAliasMapper
        tableName: sys_category
        routeFieldName: slug
      tag_name:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_tag
        routeFieldName: slug
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nDisallow: /typo3_src/\r\nAllow: /typo3/sysext/frontend/Resources/Public/*\r\n\r\n# Only allow URLs generated with RealURL\r\nDisallow: /*?id=*\r\nDisallow: /*&id=*\r\n\r\n# L=0 is the default language\r\nDisallow: /*?L=0*\r\nDisallow: /*&L=0*\r\n\r\n# typeNum = 98 is usually the print version.\r\nDisallow: /*?type=98*\r\nDisallow: /*&type=98*\r\n\r\n# Should always be protected (.htaccess)\r\nDisallow: /*/Private/*\r\nDisallow: /*/Configuration/*\r\nDisallow: /*/Initialisation/*\r\n\r\nAllow: /fileadmin/generic_lib/Resources/Public/*\r\n\r\nDisallow: /typo3temp/*\r\nAllow: /typo3temp/*.css\r\nAllow: /typo3temp/*.css.*.gzip\r\nAllow: /typo3temp/*.js\r\nAllow: /typo3temp/*.js.*.gzip\r\nAllow: /typo3temp/*.jpg\r\nAllow: /typo3temp/*.gif\r\nAllow: /typo3temp/*.png\r\n\r\nDisallow: *.sql\r\nDisallow: *.sql.gz\r\n\r\n\r\nSitemap: https://example.com/sitemap.xml\r\n\r\nUser-agent: EmailCollector\r\nDisallow: /"
websiteTitle: ''
